name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish:
    # Only run if a tag was pushed
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          make_latest: true
          files: awsh
